- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check if user exists
    ansible.buitin.command: id expense
    register: USER
    ignore_errors: true
  - name: user i/p
    ansible.buitin.debug:
      msg: user info {{USER}}
  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
  - name: print 
    ansible.buitin.debug:
      msg: "say hello"        

