- name: filters
  hosts: web
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello {{course | default('ansible')}}"
- name: upper case
  hosts: web
  vars:
    greetings: "good morning"
  tasks:
  - name: convert to uppercase
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"
- name: lower case
  hosts: web
  vars:
    greetings: "good morning"
  tasks:
  - name: convert to lowercase
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"
- name: remove duplicates
  hosts: web
  vars:
    numbers: "22 23 24 22 22 22 23 24"
  tasks:
  - name: eliminate duplicate nos
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"
- name: min & max
  hosts: web
  vars:
    greetings: "1 12 12 55"
  tasks:
  - name: pickup min & max age
    ansible.builtin.debug:
      msg: "max age: {{ages | max}}, min age: {{ages | min}}"
- name: convert dict to items
  hosts: web
  vars:
    my_dict:
      course: ansible
      tutor: siva
      duration: 120hrs
  tasks:
  - name: before converting
    ansible.builtin.debug:
      msg: "before converting: {{ my_dict }}"
  - name: after converting
  ansible.builtin.debug:
    msg: "after converting: {{ my_dict | dict2items }}"
- name: convert items to dict
  hosts: web
  vars:
    my_list:
    - {'key': 'course', 'value': 'devops'}
    - {'key': 'tutor', 'value': 'siva'}
    - { 'key': 'duration', 'value': '120 hrs'}
  tasks:
  - name: before converting
    ansible.builtin.debug:
      msg: "before converting: {{ my_list }}"
  - name: after converting
  ansible.builtin.debug:
    msg: "after converting: {{ my_dict | items2dict }}"        
            
                        
